# -*- coding: utf-8 -*-
"""Change_Style.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pk6wqTy8HIzBzCtD3aRI1T0ZYgKYRhTM
"""

import matplotlib.pyplot as plt

import numpy as np
import math

x= np.arange(0 , math.pi*2 , 0.05)
y = np.sin(x)
plt.plot(x,y)
z= np.cos(x)
plt.plot(x,z,'g--')


# plt.xlabel('angle')
# plt.ylabel('sine')
# plt.title('Sine wave')

plt.show()