# -*- coding: utf-8 -*-
"""Exercise(Dot).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1081hmRLrGyB-er3RbDVf2wEwbHSfUzWU
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.arange(-100,100,10)
y = 3*x*x + 5*x +10

plt.plot(x,y, 'r.')
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Graph')
plt.show()