# -*- coding: utf-8 -*-
"""Exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jz8z-KvLJMixktYwWIb5u0Co6aG64MlW
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.arange(-100,100,10)
y = 3*x*x + 5*x +10

plt.plot(x,y)
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Graph')
plt.show()