# -*- coding: utf-8 -*-
"""Multiple Plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tAPefxbz9kHZfNVDFohQekeE1g6Ljhwl
"""

import matplotlib.pyplot as plt
fig,axes =  plt.subplots(2,3) # subplots(rows, columns), this function returns
                              # two values, fig and axes, we are interested
                              # in axes

import numpy as np
x = np.arange(1,5,0.2)        # an array with values 1, to 5 with 0.2 steps
axes[0][0].plot(x,x*x)        # first plot function at (0,0)
axes[0][0].set_title('square')
axes[0][1].plot(x,np.sqrt(x))  # plot at (0,1)
axes[0][1].set_title('square root')
axes[0][2].plot(x,np.exp(x))  # plot at (0,2)
axes[0][2].set_title('exp')
axes[1][0].plot(x,np.log10(x)) # plot at (1,0)
axes[1][0].set_title('log')
axes[1][1].plot(x, 2*x + 5)    # plot at (1,1)
axes[1][1].set_title("Linear")
axes[1][2].plot(x, 2*x**2 - 11*x + 10) # plot at (1,1)
axes[1][2].set_title("Polynomial")
plt.tight_layout()   # spaces out the plots

plt.show() # display all the plots