# -*- coding: utf-8 -*-
"""Read Image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WpVth5g0A98bx5xnhECG8KNwhnbRhhQo
"""

! curl https://i.postimg.cc/rFLs6ysm/sliit.png --output sliit.png
! curl https://i.postimg.cc/GtLfYszt/butterfly.jpg --output butterfly.jpg
! curl https://i.postimg.cc/7LqSqML5/obama.jpg --output obama.jpg

import matplotlib.pyplot as plt
import matplotlib.image as img # take image class of matplotlib as img

import numpy as np

# please upload this file to your folder
image = img.imread('sliit.png')
plt.imshow(image)
plt.colorbar()