# -*- coding: utf-8 -*-
"""Seperating an image to 3 colour channels.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QF8as1ZCXKXlm1peO9Y-XNPVz0ychUm4
"""

! curl https://i.postimg.cc/rFLs6ysm/sliit.png --output sliit.png
! curl https://i.postimg.cc/GtLfYszt/butterfly.jpg --output butterfly.jpg
! curl https://i.postimg.cc/7LqSqML5/obama.jpg --output obama.jpg

import matplotlib.pyplot as plt
import matplotlib.image as img
import numpy as np

image = img.imread('obama.jpg')
fig, axes = plt.subplots(2,3, figsize =(7,7))

axes[0][0].imshow(image[:,:,0],cmap='Reds') # Red Channel
axes[0][1].imshow(image[:,:,1],cmap='Greens') # Green Channel
axes[0][2].imshow(image[:,:,2],cmap='Blues') # Blue Channel
axes[1][0].imshow(image[:,:,0],cmap='gray') # Red Channel in gray colour
axes[1][1].imshow(image[:,:,1],cmap='gray') # Green Channel in gray colour
axes[1][2].imshow(image[:,:,2],cmap='gray') # Blue Channel in gray colour

plt.tight_layout()   # spaces out the plots
plt.show() # display all the plots