# -*- coding: utf-8 -*-
"""Simple _Plot of Graph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E6kzgSTQ_XNnV8S7TUOHLAX0JYYsxfNg
"""

import matplotlib.pyplot as plt

x = [1 ,2 ,3 ,4 ,5]
y = [5, 15 ,35, 47, 52]

plt.plot(x,y)
plt.ylabel('Scores')
plt.xlabel('Nos')
plt.title("Simple XY Graph")
plt.show()